Add some options and error handling to regenerate_bazel_completion

diff --git a/bashrc.d/003-bazel-helpers b/bashrc.d/003-bazel-helpers
--- a/bashrc.d/003-bazel-helpers
+++ b/bashrc.d/003-bazel-helpers
@@ -2,13 +2,50 @@
 
 regenerate_bazel_completion () {(
     set -e
-    pushd $1
+
+    usage () {(
+        echo -e "Function to regenerate bazel tab completion"
+        echo -e "Usage: regenerate_bazel_completion [-h] <path>"
+        echo -e "       -h: prints this message"
+        echo -e "       -v: version of bazel to use"
+        echo -e "   <path>: path to a directory containing a .bazelversion file"
+        echo -e "           (not used if -v is used)"
+    )}
+
+    local OPTIND myopt h
+    while getopts ":hv:" opt ; do
+        case "${opt}" in
+            h) usage
+               exit 0
+                ;;
+            v) VERSION=${OPTARG}
+                ;;
+            ?) echo -e "Invalid option."
+               usage
+               exit 1
+                ;;
+        esac
+    done
+    shift $((OPTIND-1))
+
+    if [ -z "$VERSION" ]; then
+        if [ -z "$1" ]; then
+            echo "No path or version specified"
+            usage
+            exit 1
+        fi
+        if [ ! -f $1/.bazelversion ]; then
+            echo "Missing .bazelversion file in $1"
+            exit 1
+        fi
+        VERSION=$(cat $1/.bazelversion)
+    fi
+
     rm -f ~/.bazelcomplete
 
-    curl -fsSL https://raw.githubusercontent.com/bazelbuild/bazel/$(cat .bazelversion)/scripts/bazel-complete-header.bash >> ~/.bazelcomplete
-    curl -fsSL https://raw.githubusercontent.com/bazelbuild/bazel/$(cat .bazelversion)/scripts/bazel-complete-template.bash >> ~/.bazelcomplete
+    curl -fsSL https://raw.githubusercontent.com/bazelbuild/bazel/${VERSION}/scripts/bazel-complete-header.bash >> ~/.bazelcomplete
+    curl -fsSL https://raw.githubusercontent.com/bazelbuild/bazel/${VERSION}/scripts/bazel-complete-template.bash >> ~/.bazelcomplete
     bazel help completion >> ~/.bazelcomplete
-    popd
     source ~/.bazelcomplete
 )}
 
